# Generated by Django 5.2.14 on 2026-05-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
