# Generated by Django 5.2.14 on 2026-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_error',
            field=models.TextField(blank=True),
        ),
    ]
