# Generated by Django 5.2.14 on 2026-05-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pedido_fecha_asignado_pedido_fecha_en_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_referencia_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_referencia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
