# Generated by Django 5.2.14 on 2026-05-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cliente_foto_referencia_actualizada_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape')], default='PENDIENTE', max_length=20),
        ),
    ]
