# Generated by Django 5.2.14 on 2026-05-26 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pedido_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.lugar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='core.lugar'),
        ),
    ]
