# Generated by Django 5.2.14 on 2026-05-26 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_lugar_alter_pedido_metodo_pago_cliente_lugar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago_final',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_pago_registrado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('FIADO', 'Fiado')], default='PENDIENTE', max_length=20),
        ),
    ]
