# Generated by Django 5.2.14 on 2026-05-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pedido_fecha_pago_pedido_metodo_pago_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia'), ('FIADO', 'Fiado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago_final',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, null=True),
        ),
    ]
